### ISSUE TITLE
Trailing whitespace after class name problem

### ISSUE THREAD

**Issue by tmpfs** [reshape/standard#12]
It appears to me that if there is trailing whitespace at the end of a class name the generated HTML nesting is not correct.

For example if I have:

```
ul.info 
  li Item
```

Noting that the class name `info` is followed by a single space character, I end up with markup like:

```
<ul class="info "></ul>
<li>Item</li>
```

I think in this instance that `reshape-standard` could deal with this more gracefully, it took me a little bit of head scratching to work out why the nesting was wrong ;)

I also don't recall ever running into this issue with `jade` which I believe this standard plugin has borrowed from.

Thanks for reshape - really enjoying it so far :)

**Comment by jescalan** [comment]
Hi @tmpfs -- thanks for the heads up on this! I'll get it patched early next week 😁

**Comment by tmpfs** [comment]
Awesome :) Ah, my bad, I shall move the issue, always good to be in the right place ;)
