### ISSUE TITLE
SugarML is not the default parser?

### ISSUE THREAD

**Issue by olstenlarck** [reshape/standard#44]
Heya! I strongly believe that SugarML is not the default, cuz i don't see it as dependency here, nor in `reshape` - from here (reshape-standard) it just pass `options.parser` directly to the `reshape`.

I'll try it now, but to have it listed as issue ;d

**Comment by olstenlarck** [comment]
Yup, i'm right. We should update the README :)

**Comment by jescalan** [comment]
You certainly are! Any interest in a PR to update it? Thanks for catching this 👬

**Comment by drewwestrick** [comment]
I'm having the same issue. Went ahead and created a pull request to move sugarml from devDep back to regular dep: https://github.com/reshape/standard/pull/47.

**Comment by jescalan** [comment]
Hey so just to be clear, sugarml is not the default, and isn't intended to be. The readme reflects that sugarml is not the default, and also contains a line on how to add it in, if you want 😁
